### PR TITLE
Correct version checks of Ansible and Python

### LINKED ISSUE #786: mitogen_ansible compares ansible.__version__ without parsing it
`ansible.__version__` is a string that contains the release version of Ansible, as a string (e.g. `"2.10.0"`), ansible_mitogen contains several checks against this to decide on behaviours. These worked up to and including Ansible 2.9, but they are incorrect for 2.10 onward.

I have a patch in the works.

### PR DESCRIPTION
**Pull request by moreati**
Checks were performed using character by character string comparisons. This gives incorrect results when checking Ansible 2.10, because '2.10' < '2.9'.

Fixes #786

### CODE REVIEW

**Review by s1113950 — CHANGES_REQUESTED** [review]
Future Mitogen will only support Ansible 2.10+, so we can remove old checks against old versions of Ansible :)

**Comment by moreati** [comment]
I don't want to remove Ansible 2.8 & 2.9 support from master permanently. I'm working on a branch to restore it.

**Comment by s1113950** [comment]
🤔 Ansible 2.8 was EOL a week ago: https://access.redhat.com/support/policy/updates/ansible-engine ; also 2.8's API is quite different from 2.10+. What's the motivation for supporting a dead Ansible version?

**Comment by moreati** [comment]
> thinking Ansible 2.8 was EOL a week ago: https://access.redhat.com/support/policy/updates/ansible-engine ; also 2.8's API is quite different from 2.10+.

and even Ansible 2.10 had it's final release in the last few days https://groups.google.com/g/ansible-announce/c/6_AmfDp2fCw. Ansible 2.9 might hang around longer, for RHEL customers?

> What's the motivation for supporting a dead Ansible version?

How I imagined migrating to Mitogen 0.3 for my projects, in 2 change-one-thing-at-a-time steps, e.g.
1. Upgrade to Mitogen 0.3.x, keeping Ansible 2.y
2. Upgrade to Ansible 2.y+z, keeping Mitogen 0.3.x

I'm less enamoured with the idea of supporting Ansible 2.8 now (and the maintenance burden). Maybe there's a case for 2.9, maybe. Regardless, I still wish to fix any string based version comparisons.

**Comment by dw** [comment]
> Future Mitogen will only support Ansible 2.10+, so we can remove old checks against old versions of Ansible :)

Don't remove any backwards compatibility code unless it has been thoroughly discussed on a case-by-case basis. Upstream have a horrendous compatibility culture (inherited to a degree from the surrounding ecosystem) that should not leak into this project.

We agreed to conditionally damage backwards compatibility for as long as nobody in the short term exists who is willing to do the work necessary to restore it, but no agreement was made to change compatibility policy for the project as a whole, and certainly no agreement to intentionally remove existing compatibility work.

Separately, the cost of multiple development branches is very much non-trivial for everyone. Starting from installation instructions, OS distributions (Mitogen is packaged in many places), and finally the cost of maintaining multiple distinct versions of the software each with their own testing.

> thinking Ansible 2.8 was EOL a week ago

Regardless of the tragic upstream policies, user playbooks do not suddenly cease to exist because someone decided to externalize costs, nor is it reasonable to require the cost of forced obsolescence to be paid down particularly where it is so easily avoided. It is an abusive bullying tactic, and by adopting upstream policies we enable this abuse.

**Comment by moreati** [comment]
> Don't remove any backwards compatibility code unless it has been thoroughly discussed on a case-by-case basis

In that case, we might need to revert #785.

> Separately, the cost of multiple development branches is very much non-trivial for everyone.

Agreed, I don't enjoy cherry-picking.

**Pull request closed without merging**
