### PR TITLE
Ansible 7 (core 2.14) support, AnsibleUnsafeText fixes

### PR DESCRIPTION
**Pull request by moreati**
Rather than allowing `AnsibleUnsafeText` to be pickled/unpickled this PR adds `ansible_mitogen.utils.unsafe.cast()` to cast them back to plain strings before sending to the target. This follows the implicit behaviour of plain Ansible, in which serialising to JSON then deserialising has the same effect.

Thanks to @opoplawski for PR #977 on which this is based, and @AKrumov for investigation in #1034.

### CODE REVIEW

**Comment by doobry-systemli** [comment]
Thanks a lot for looking into this @moreati!

**Comment by guenhter** [comment]
@moreati Any update on this? Is there something holding this back?

**Comment by dj-wasabi** [comment]
And what about using 2.15? Or do I have to create a seperate issue for?

**Comment by hishamanver** [comment]
LGTM! <3

**Comment by ialmahi22** [comment]
@moreati Thanks for looking into this, we're using Ansible 2.14 and after this PR, is there any pending updates on it?

**Comment by opoplawski** [comment]
Fixes #974

**Comment by huyz** [comment]
I'm trying this out (first time trying out Mitogen actually) and I get an error fairly early in my playbook.

My task is:
```ansible
    - name: Add to authorized_keys the content of {{ pub_files_for_ssh }}
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', item) }}"
        comment: >-
          {{ item
            | replace('~/.ssh/+', '+')
            | replace('~/.ssh/', '+' + controller_hostname + '/')
            | replace('.pub', '')
            | trim }} (by ansible@{{ controller_hostname }})
      loop: "{{ pub_files_for_ssh }}"
```

Looks like there's a problem while invoking the `lookup` command:
```log
File lookup using /Users/huyz/.ssh/id_ed25519.pub as file
[task 72194] 12:26:27.559050 D ansible_mitogen.process: will use multiplexer 0 (/var/folders/cd/80666smx571dkz_nttfhf7dw0000gn/T/mitogen_unix_oqpc2g0s.sock) to connect to "tmac"

[…]

[mux  72009] 12:26:27.632176 D mitogen.io: SetupProtocol(ssh.tmac).on_receive()
[mux  72009] 12:26:27.632602 D mitogen.parent: ssh.tmac: (unrecognized): hostname contains invalid characters

[…]

[mux  72009] 12:26:27.636263 D mitogen: <Side of ssh.tmac fd 117>: empty read, disconnecting
[mux  72009] 12:26:27.636533 D mitogen.parent: failing connection ssh.tmac due to EofError('EOF on stream; last 100 lines received:\nhostname contains invalid characters\r')
[mux  72009] 12:26:27.636799 D mitogen.parent: PopenProcess ssh.tmac pid 72244: exited with return code 255

[…]

TASK [Add to authorized_keys the content of ['~/.ssh/id_ed25519.pub'] ********************************************************************************************************************************************************************
failed: [tmac] (item=~/.ssh/id_ed25519.pub) => {
    "ansible_loop_var": "item",
    "item": "~/.ssh/id_ed25519.pub",
    "msg": "EOF on stream; last 100 lines received:\nhostname contains invalid characters\r",
    "unreachable": true
}

```

**Comment by moreati** [comment]
> I'm trying this out (first time trying out Mitogen actually) and I get an error fairly early in my playbook.

Could you reduce this to a Minimal Reprodicing Example? It's difficult to say what is causing the failure in your pasted code - without knowing values of the variables involved.

Could you also comfirm whether the latest release of Mitogen (0.3.5) exhibits the same error? You may need to try it with an earlier release of Ansible.

**Comment by huyz** [comment]
@moreati I think I was able to get it to work. I was doing `-e strategy=mitogen_free` instead of `ANSIBLE_STRATEGY=mitogen_free`. Thanks!

**Pull request merged**
