### PR TITLE
tests: Move test container images to Amazon Elastic Container Registry

### LINKED ISSUE #791: Docker Hub rate limiting is making CI tests flaky
e.g.  https://travis-ci.org/github/dw/mitogen/jobs/753779697

> ff50d722b382: Retrying in 2 seconds
> ff50d722b382: Retrying in 1 second
> toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
> The command ".ci/${MODE}_install.py" failed and exited with 1 during .

From https://www.docker.com/increase-rate-limit

> On November 20, 2020, rate limits anonymous and free authenticated use of Docker Hub went into effect. Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours. 

Possible mitigations or fixes
- Use authenticated requests. Currently Mitogen requests are counted along with all other anonymous requests from the same IP.
  - Who's account? 
- Upgrade to a premium Docker account
  - Paid for by who?
  - Can we embed a secret/token in the repo, given constraints?
- Switch to an alternative container registry
- Reduce Docker Registry usage
  - Perhaps with caching, or pinning?

### PR DESCRIPTION
**Pull request by moreati**
fixes #791

### CODE REVIEW

**Comment by moreati** [comment]
Still hitting rate limiting on AWS ECR, but over a shorter time period, and I might be able to create a read-only token that increases that limit

From https://github.com/mitogen-hq/mitogen/pull/790/checks?check_run_id=1745766546

> Error response from daemon: toomanyrequests: Rate exceeded

> You may receive a 429: Too Many Requests error or a ThrottleException error from one or more Amazon ECR commands or API calls. If you are using Docker tools with Amazon ECR, then for Docker versions 1.12.0 and greater, you may see the error message TOOMANYREQUESTS: Rate exceeded. For versions of Docker below 1.12.0, you may see the error Unknown: Rate exceeded.
> This indicates that you are calling a single endpoint in Amazon ECR repeatedly over a short interval, and that your requests are getting throttled. Throttling occurs when calls to a single endpoint from a single user exceed a certain threshold over a period of time.
> Various API operations in Amazon ECR have different throttles.
> For example, the throttle for the GetAuthorizationToken action is 20 transaction per second (TPS), with up to a 200 TPS burst allowed. In each region, each account receives a bucket that can store up to 200 GetAuthorizationToken credits. These credits are replenished at a rate of 20 per second. If your bucket has 200 credits, you could achieve 200 GetAuthorizationToken API transactions per second for one second, and then sustain 20 transactions per second indefinitely. 
-- https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html

**Comment by luiscachog** [comment]
Another option could be [https://quay.io](https://quay.io)

**Comment by moreati** [comment]
> Another option could be https://quay.io

Thank you, but unfortunately Quay is a paid service, and the project doesn't have a budget at this time.

**Review by s1113950 — APPROVED** [review]

**Comment by moreati** [comment]
To be clear, this is not a permanent solution. It's a snapshot running under my personal AWS account, with a bus factor of one. I need to work out something more permanent, and shared.

**Pull request merged**
