### PR TITLE
minimal patch to support ansible-core 2.11

### LINKED ISSUE #834: ansible-core 2.11 support?
Hi, I don't see an existing issue so creating one. Are there plans to support ansible 2.11? Thank you.

```
ERROR! Your Ansible version (2.11.0) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 10).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.

    https://mitogen.rtfd.io/en/latest/changelog.html
    https://github.com/dw/mitogen/issues/
```

### PR DESCRIPTION
**Pull request by upekkha**
Fixes #834

### CODE REVIEW

**Comment by jauderho** [comment]
Are there any plans to add 2.11 support to mitogen anytime soon?

**Comment by bradh352** [comment]
I haven't tested this yet, I'm on 2.10,  but are there any known deficiencies on 2.11 using this patch?

@upekkha @moreati

**Comment by apple4ever** [comment]
I've been using it for a couple of months, but admittedly I stay pretty close to standard Ansible (for example, I don't use any collections).

**Comment by philfry** [comment]
I use this patch for a while now with some collections like containers.podman, community.crypto, community.libvirt, netbox.netbox and some self-made collections etc, also with ssh jumphosts, and I'm not experiencing any problems yet (apart from an incompatibility between ansible 2.11 and netbox.netbox that unrelated to mitogen).

**Comment by GhostLyrics** [comment]
I use this successfully with:
- ansible.posix
- community.crypto
- community.general
- community.mysql
- mgit_at.mgssl

**Comment by moreati** [comment]
@upekkha Thank you for this much needed fix, and sorry for the slow reply. My current thinking is that this still needs some work

- [ ] Continuous Integration coverage with Ansible 2.11
- [ ] A changelog entry
- [ ] Updates to documentation that mentions Ansible versions

Are you still interested in refining this patch?

**Comment by GhostLyrics** [comment]
I'm willing to help with the listed items if @upekkha finds themselves short of time.

**Comment by upekkha** [comment]
It's a pity, but I'm glad if someone else can finalize and polish the PR.

**Comment by moreati** [comment]
superceded by #870

**Pull request closed without merging**
