### PR TITLE
Add podman transport

### PR DESCRIPTION
**Pull request by jordemort**
Continuing in the spirit of https://github.com/dw/mitogen/pull/595, in this PR I copy and paste the `docker` transport to add a `podman` transport.

[Podman](https://github.com/containers/libpod) is mostly a drop-in replacement for the Docker CLI, so this is really just a copy, paste, search, replace exercise.

This is completely untested as of yet, but I wanted to let you know I was working on it. I'll take the PR out of draft mode when it is ready for review.

### CODE REVIEW

**Comment by jordemort** [comment]
(Of course, any feedback before I take it out of draft mode is also welcome and solicited)

**Comment by moreati** [comment]
@jordemort please could you update this to current master. Otherwise, may I update this branch on your behalf?

**Comment by jordemort** [comment]
@moreati Please feel free, I've switched employers since I started this and no longer work on the tool I needed it for. It's almost literally a search/replace of the docker transport, so it shouldn't be too hard to recreate a version based on current master.

**Comment by wouterhummelink** [comment]
I'm very anxious to have the podman transport working. At current job we use mitogen to accelerate molecule pipelines which doesn't work for RHEL8, that no longer has docker as a supported option.
Let me know what I can to to help here

**Comment by wouterhummelink** [comment]
I've tested this PR branch locally and mitogen works like a charm except for #776

**Comment by wouterhummelink** [comment]
One issue, if ansible fails on a task the following errors are logged after the run:
```
ERROR! [mux  1530681] 11:53:59.032568 E mitogen: podman.instance-1001: Corruption detected: frame signature incorrect. This likely means some external process is interfering with the connection. Received:

 

b'Error: exec session exited with non-zero exit code 143: OCI runtime error\n'
ERROR! [mux  1530681] 11:53:59.091595 E mitogen: podman.instance-1001: Corruption detected: frame signature incorrect. This likely means some external process is interfering with the connection. Received:

 

b'Error: exec session exited with non-zero exit code 143: OCI runtime error\n'
```

**Comment by jordemort** [comment]
I'm not going to come back to finish this any time soon, so I'm going to close this PR to avoid discouraging anyone else from working on it.

I think the CLI is close enough that instead of actually needing a Podman-specific transport, it might be reasonable to just use the existing Docker one and point it at the `podman` binary - all this PR ever was was a find/replace of docker to podman on the existing Docker code.

**Pull request closed without merging**
