### PR TITLE
Python 3.12 support

### PR DESCRIPTION
**Pull request by moreati**

### CODE REVIEW

**Comment by psvmcc** [comment]
Hi, just checked, my setup:
```
ansible [core 2.16.4]
  config file = /Users/ps/infra/ansible.cfg
  configured module search path = ['/Users/ps/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ps/infra/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/ps/infra/.collections
  executable location = /Users/ps/infra/.venv/bin/ansible
  python version = 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/Users/ps/infra/.venv/bin/python)
  jinja version = 3.1.3
  libyaml = True

# git+https://github.com/moreati/mitogen.git@docs-download-url
mitogen                   0.3.5.dev0
```

ANSIBLE_VERSION_MAX patched to 2.16

Packaged modules(dnf/apt/...) doesn't works:
```
ANSIBLE_STRATEGY=mitogen_linear ansible localhost -m package -a 'pkg=vim' -D -C -i localhost, --check
```
output:
```
    "msg": "Unexpected failure during module execution: mitogen.core.StreamError: cannot unpickle 'ansible.utils.unsafe_proxy'/'AnsibleUnsafeText'\n  File \"<stdin>\", line 3868, in _dispatch_one\n  File \"<stdin>\", line 3851, in _parse_request\n  File \"<stdin>\", line 998, in unpickle\n  File \"<stdin>\", line 789, in find_class\n  File \"<stdin>\", line 899, in _find_global\n",
```

Hotfix in https://github.com/mitogen-hq/mitogen/issues/1034#issuecomment-1851557386 fixes this issue.

I'm not sure, it related or not to this MR.

I don't see any other issues here.

**Comment by moreati** [comment]
> python version = 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/Users/ps/infra/.venv/bin/python)
> mitogen  git+https://github.com/moreati/mitogen.git@docs-download-url
> ANSIBLE_VERSION_MAX patched to 2.16
...
> > Unexpected failure during module execution: mitogen.core.StreamError: cannot unpickle 'ansible.utils.unsafe_proxy'/'AnsibleUnsafeText' ...
> 
> I don't see any other issues here.

Thanks, that's good to hear. My rough plan is to release 0.3.5 with this, followed by 0.3.6 with newer Ansible support.

**Comment by upekkha** [comment]
Same here: no issues so far. (Python 3.12.2, Ansible 9.3.0, this mitogen branch with the manual patch above.)

**Comment by azmeuk** [comment]
Hi @moreati.
Nice to see that you have a bit of time to spend on mitogen, and thank you for the hard work :pray:
I just tried to check the py312 PR after your call for comments on mastodon, but I am stuck to 0.3.3 because of #726. Any attempt to any of my servers fails with a `sudo password is incorrect` error with the master branch or this PR + python 3.12.

**Comment by philfry** [comment]
Great to see this project is still alive, many thanks @moreati!

I tested this pr together with #833, #991, https://github.com/mitogen-hq/mitogen/issues/1034#issuecomment-1851557386 and bumping ANSIBLE_VERSION_MAX to 2.16 on Fedora 39 (controller node) and OracleLinux 8 & 9 (managed nodes). Works without any errors :+1:

**Pull request merged**
