### PR TITLE
Fixes RuntimeWarning for improper buffering on local connection in Python 3.8+

### PR DESCRIPTION
**Pull request by MetricMike**
```bash
[mux  24512] 18:54:08.981562 D mitogen.io: EpollPoller.poll(29.704136800002743)
/home/metricmike/.asdf/installs/python/3.8.5/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
```
Change in Python 3.8 is described at https://bugs.python.org/issue32236
tl;dr - python used to silently ignore `open(fd, 'rb', 1)` on binary mode, now they don't because it could potentially cause issues

During the Python3 port, mitogen switched a file descriptor at (https://github.com/dw/mitogen/commit/410016ff479b717b2066cb3e1c673658d1ab43fe#diff-3540c3617f4566023f000914cebe2d71L1764-R1831) from text to binary mode on this commit, but left line buffering on. As far as I can tell, this is the only file descriptor where both the mode and buffering option didn't remain consistent on that commit.
image

When building from this commit, the warning goes away and my not super trivial playbook runs successfully so this should solve issues #691 and #720, but I ran into several issues while building/testing and would appreciate some help verifying:
- Python 3.8 breaks at least the CFFI version used in `tests/requirements.txt`. Bumping that to 1.14.2 allows `.ci/localhost_ansible_install.py` to finish.
- Ubuntu 18.04 and up remove /usr/bin/python, so I needed to alias that to python3 in order to get `.ci/localhost_ansible_tests.py` to partially pass
- brew is expected but not installed for `.ci/localhost_ansible_tests.py`
- `.ci/*` expect a clean machine and I was building/testing locally

### CODE REVIEW

**Comment by s1113950** [comment]
`.ci/localhost_ansible_tests.py` is only used for Mac tests, not too sure why but it was that way before I started on the project and I haven't had the time to standardize the test framework since. 

Unfortunately, Mitogen tests don't really work super well ran locally. Definitely something that needs fixing up! What I've done in the meantime is make my own little test lib here: https://github.com/s1113950/mitogen-test where I run a certain `.yml` file in a container that gets created on the fly (or locally if desired). It's not perfect but it's faster for rapid dev than waiting for Mitogen's whole test suite to finish.

**Comment by s1113950** [comment]
I got the same error you got on another PR! https://github.com/dw/mitogen/pull/715 --> https://dev.azure.com/dw-mitogen/Mitogen/_build/results?buildId=985&view=logs&j=91b5f601-2ef2-5ad3-ce48-a74a8d70b8fa&t=102d5197-072a-520e-94dd-1966b8f15f2b 

This one specifically:
```
File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 25: ordinal not in range(128)
```
when I figure it out I'll let you know

**Comment by s1113950** [comment]
@MetricMike try setting these env vars: `LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8`

**Comment by moreati** [comment]
I just encountered the same error while expanding coverage of Tox tests (follow on to #762). Changing the same line does remove the repeated `RuntimeWarning`s. I don't pretend to understand the file descriptor juggling that Mitogen does, and I don't know if buffering=0, as opposed to default buffering is the right thing.

**Comment by moreati** [comment]
I'd like to merge #775 before this

**Comment by moreati** [comment]
@MetricMike please could you update this to current master. Otherwise, may I update this branch on your behalf?

**Comment by MetricMike** [comment]
rebase failed - will try to address this weekend but otherwise feel free to update :)

**Comment by MetricMike** [comment]
I missed the 0.2.10 / 0.3.0 split. Latest commits should pass CI.

Can this get added to #800 as well?

**Comment by moreati** [comment]
Shouldn't be a problem, sorry for the wait.

**Pull request merged**
